apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- list "common" . | include "bitwarden.labels.selector" | nindent 4 }}
  name: bitwarden-config
type: Opaque
data:
  globalSettings__duo__aKey: {{ .Values.duoAkey | b64enc }}
  globalSettings__hibpApiKey: {{ .Values.hibpApiKey | b64enc }}
  globalSettings__identityServer__certificatePassword: {{ .Values.identity.certificatePassword | b64enc }}
  globalSettings__installation__id: {{ .Values.installationId | b64enc }}
  globalSettings__installation__key: {{ .Values.installationKey | b64enc }}
  globalSettings__internalIdentityKey: {{ .Values.internalIdentityKey | b64enc }}
  globalSettings__mail__smtp__password: {{ .Values.mail.password | b64enc }}
  globalSettings__mail__smtp__username: {{ .Values.mail.username | b64enc }}
  globalSettings__oidcIdentityClientKey: {{ .Values.oidcIdentityClientKey | b64enc }}
  globalSettings__sqlServer__connectionString: {{ printf "Data Source=tcp:bitwarden-mssql,1433;Initial Catalog=vault;Persist Security Info=False;User ID=sa;Password=%s;MultipleActiveResultSets=False;Connect Timeout=30;Encrypt=True;TrustServerCertificate=True" .Values.mssql.databasePassword | b64enc }}
  globalSettings__yubico__clientId: {{ .Values.yubico.clientId | b64enc }}
  globalSettings__yubico__key: {{ .Values.yubico.key | b64enc }}
